"""RunStore port: the persistence interface platform modules depend on.

Defines one Protocol per entity repository plus the ``RunStore`` UnitOfWork
container, so callers can depend on these abstractions rather than the concrete
SqlAlchemy implementation.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from domain import (
    AgentRun,
    AgentSpec,
    AgentStage,
    CallbackDelivery,
    Conversation,
    LogEvent,
    ModelCallRecord,
    SkillSpec,
    ToolSpec,
)
from domain.enums import CallbackStatus, RunStatus

# ---------------------------------------------------------------------------
# Per-entity repository protocols
# ---------------------------------------------------------------------------


class RunRepositoryProtocol(Protocol):
    def create(self, run: AgentRun, *, conn: Any | None = None) -> AgentRun: ...
    def get(self, run_id: str) -> AgentRun | None: ...
    def get_by_request_id(self, caller: str, route_tag: str, request_id: str) -> AgentRun | None: ...
    def update(self, run: AgentRun, *, conn: Any | None = None) -> AgentRun: ...
    def update_if_current(
        self,
        run: AgentRun,
        *,
        expected_statuses: set[RunStatus] | frozenset[RunStatus],
        expected_worker: str | None = None,
        match_worker: bool = False,
        conn: Any | None = None,
    ) -> bool: ...
    def list(self, limit: int = 100) -> list[AgentRun]: ...
    def list_filtered(
        self,
        *,
        statuses: list[RunStatus] | None = None,
        route_tag: str | None = None,
        caller: str | None = None,
        agent_name: str | None = None,
        search: str | None = None,
        limit: int = 200,
    ) -> list[AgentRun]: ...
    def list_by_status(self, statuses: list[RunStatus], limit: int = 100) -> list[AgentRun]: ...
    def claim_ready(self, *, worker_id: str, lease_seconds: float, limit: int = 20) -> list[AgentRun]: ...
    def renew_lease(self, run_id: str, *, worker_id: str, lease_seconds: float) -> bool: ...
    def status_counts(self) -> dict[str, int]: ...
    def list_by_conversation(self, conversation_id: str, limit: int = 100) -> list[AgentRun]: ...
    def agent_metrics_summary(self) -> dict[str, dict[str, object]]: ...


class ConversationRepositoryProtocol(Protocol):
    def create(self, conversation: Conversation, *, conn: Any | None = None) -> Conversation: ...
    def get(self, conversation_id: str) -> Conversation | None: ...
    def get_by_external_id(self, caller: str, external_id: str) -> Conversation | None: ...
    def update(self, conversation: Conversation, *, conn: Any | None = None) -> Conversation: ...


class StageRepositoryProtocol(Protocol):
    def get_or_create(self, stage: AgentStage, *, conn: Any | None = None) -> AgentStage: ...
    def get(self, run_id: str, stage_key: str) -> AgentStage | None: ...
    def list_for_run(self, run_id: str) -> list[AgentStage]: ...
    def begin_attempt(
        self, run_id: str, stage_key: str, *, run_attempt: int, execution_id: str
    ) -> AgentStage | None: ...
    def save_checkpoint(
        self, run_id: str, stage_key: str, *, execution_id: str, checkpoint: dict[str, Any]
    ) -> bool: ...
    def mark_succeeded(self, run_id: str, stage_key: str, *, execution_id: str, output: Any) -> bool: ...
    def mark_failed(
        self, run_id: str, stage_key: str, *, execution_id: str, error_type: str, error_message: str
    ) -> bool: ...
    def mark_canceled(self, run_id: str, stage_key: str, *, execution_id: str) -> bool: ...
    def mark_outcome_unknown(
        self, run_id: str, stage_key: str, *, execution_id: str, error_type: str, error_message: str
    ) -> bool: ...
    def begin_side_effect_once(self, run_id: str, stage_key: str, *, execution_id: str) -> AgentStage | None: ...
    def mark_side_effect_dispatched(self, run_id: str, *, idempotency_key: str, execution_id: str) -> bool: ...
    def mark_side_effect_returned(self, run_id: str, *, idempotency_key: str, execution_id: str) -> bool: ...
    def reset_failed_for_run(self, run_id: str, *, conn: Any | None = None) -> int: ...
    def delete_for_run(self, run_id: str, *, conn: Any | None = None) -> int: ...


class LogRepositoryProtocol(Protocol):
    def add(self, event: LogEvent, *, conn: Any | None = None) -> LogEvent: ...
    def for_trace(self, trace_id: str) -> list[LogEvent]: ...
    def for_run(self, run_id: str) -> list[LogEvent]: ...
    def list_by_component(self, component: str, limit: int = 100) -> list[LogEvent]: ...
    def tool_metrics_summary(self) -> dict[str, dict[str, object]]: ...


class CallbackRepositoryProtocol(Protocol):
    def save(self, delivery: CallbackDelivery, *, conn: Any | None = None) -> CallbackDelivery: ...
    def claim_pending(self, *, worker_id: str, lease_seconds: float, limit: int = 20) -> list[CallbackDelivery]: ...
    def get(self, event_id: str) -> CallbackDelivery | None: ...
    def for_run(self, run_id: str) -> list[CallbackDelivery]: ...
    def counts(self) -> dict[str, int]: ...
    def metrics_summary(self) -> dict[str, object]: ...
    def list(self, statuses: list[CallbackStatus] | None = None, limit: int = 100) -> list[CallbackDelivery]: ...


class ModelCallRepositoryProtocol(Protocol):
    def save(self, record: ModelCallRecord, *, conn: Any | None = None) -> ModelCallRecord: ...
    def for_run(self, run_id: str) -> list[ModelCallRecord]: ...
    def for_trace(self, trace_id: str) -> list[ModelCallRecord]: ...
    def list_failed(self, limit: int = 100) -> list[ModelCallRecord]: ...
    def usage_summary(self) -> dict[str, float | int]: ...
    def metrics_summary(self) -> dict[str, object]: ...
    def list(self, limit: int = 100) -> list[ModelCallRecord]: ...


class AgentConfigRepositoryProtocol(Protocol):
    def save(self, spec: AgentSpec, *, conn: Any | None = None) -> AgentSpec: ...
    def delete(self, name: str, version: str, *, conn: Any | None = None) -> None: ...
    def list(self) -> list[AgentSpec]: ...


class ToolConfigRepositoryProtocol(Protocol):
    def save(self, spec: ToolSpec, *, conn: Any | None = None) -> ToolSpec: ...
    def delete(self, name: str, version: str, *, conn: Any | None = None) -> None: ...
    def list(self) -> list[ToolSpec]: ...


class SkillConfigRepositoryProtocol(Protocol):
    def save(self, spec: SkillSpec, *, conn: Any | None = None) -> SkillSpec: ...
    def delete(self, name: str, version: str, *, conn: Any | None = None) -> None: ...
    def list(self) -> list[SkillSpec]: ...


# ---------------------------------------------------------------------------
# UnitOfWork container protocol
# ---------------------------------------------------------------------------


@runtime_checkable
class RunStore(Protocol):
    """UnitOfWork container implemented by SqlAlchemyRunStore.

    Exposes one repository per entity plus the cross-table transactional
    operations and lifecycle / maintenance methods.  Platform modules should
    depend on this protocol, not on a concrete implementation.
    """

    # -- repositories ------------------------------------------------------

    runs: RunRepositoryProtocol
    stages: StageRepositoryProtocol
    conversations: ConversationRepositoryProtocol
    logs: LogRepositoryProtocol
    callbacks: CallbackRepositoryProtocol
    model_calls: ModelCallRepositoryProtocol
    agents: AgentConfigRepositoryProtocol
    tools: ToolConfigRepositoryProtocol
    skills: SkillConfigRepositoryProtocol

    # -- lifecycle ---------------------------------------------------------

    def close(self) -> None: ...

    def unit_of_work(self) -> Any: ...

    # -- cross-table transactional operations ------------------------------

    def update_run_with_callback(
        self,
        run: AgentRun,
        delivery: CallbackDelivery | None = None,
        *,
        expected_statuses: set[RunStatus] | frozenset[RunStatus] | None = None,
        expected_worker: str | None = None,
        match_worker: bool = False,
    ) -> bool: ...

    # -- maintenance -------------------------------------------------------

    def prune(self, retention: dict[str, float]) -> dict[str, int]: ...
    def checkpoint(self, *, vacuum: bool = False) -> dict[str, object]: ...
